[package]
name = "uuid-cluster"
version = "0.1.0"
authors = ["Noah Encke <noencke@microsoft.com>"]
description = "UUID cluser handling utilities"
license = "MIT/Apache-2.0"
repository = "https://github.com/noencke/uuid-cluster"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"